<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../tools/Oxce.FixtureSupport/Oxce.FixtureSupport.csproj" />
    <ProjectReference Include="../../src/Oxce.Core/Oxce.Core.csproj" />
    <ProjectReference Include="../../src/Oxce.Engine/Oxce.Engine.csproj" />
    <ProjectReference Include="../../src/Oxce.Formats/Oxce.Formats.csproj" />
    <ProjectReference Include="../../src/Oxce.Gameplay/Oxce.Gameplay.csproj" />
    <ProjectReference Include="../../src/Oxce.Mods/Oxce.Mods.csproj" />
    <ProjectReference Include="../../src/Oxce.Rendering/Oxce.Rendering.csproj" />
    <ProjectReference Include="../../src/Oxce.Resources/Oxce.Resources.csproj" />
    <ProjectReference Include="../../src/Oxce.Savegames/Oxce.Savegames.csproj" />
    <ProjectReference Include="../../src/Oxce.Scripting/Oxce.Scripting.csproj" />
    <ProjectReference Include="../../tools/Oxce.ResourceBrowser/Oxce.ResourceBrowser.csproj" />
  </ItemGroup>
</Project>
