<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Oxce.Core/Oxce.Core.csproj" />
    <ProjectReference Include="../Oxce.Extensions.Abstractions/Oxce.Extensions.Abstractions.csproj" />
    <ProjectReference Include="../Oxce.Gameplay/Oxce.Gameplay.csproj" />
  </ItemGroup>
</Project>
