<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Oxce.Core/Oxce.Core.csproj" />
    <ProjectReference Include="../Oxce.Mods/Oxce.Mods.csproj" />
    <ProjectReference Include="../Oxce.Savegames/Oxce.Savegames.csproj" />
    <ProjectReference Include="../Oxce.Scripting/Oxce.Scripting.csproj" />
  </ItemGroup>
</Project>
