<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Oxce.Formats/Oxce.Formats.csproj" />
    <ProjectReference Include="../../src/Oxce.Mods/Oxce.Mods.csproj" />
    <ProjectReference Include="../../src/Oxce.Savegames/Oxce.Savegames.csproj" />
  </ItemGroup>
</Project>
